spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/
    username: myuser
    password: mypassword
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#          temp:
#                    use_jdbc_metadata_defaults: false
#    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  liquibase:
    enabled: true
    change-log: classpath:/liquibase/changelog-master.yml
  security:
    user:
      name: username
      password: scarypassword

